#内装構築の全体設計図

#【AWSサーバーに（2つのコンテナである「web(Django)」 と 「nginx」）を作るよ」宣言】


services:
  web:       　　　　　　 　　　　　　　　　　　　　　　　　　　　　　　　     #★1【web: エリア（Django部屋）】
    build: .　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　         #1-1今いる場所（.）にある説明書（Dockerfile）で、Django部屋の土台を組み立てろ」という指示
    volumes:                                  　　　　　　　　　　　　　        #1-2文字データ、CSS、画像を各専用倉庫に繋ぐ命令。
      - db_volume:/usr/src/app/db_data/　　　 　　　　　　　　　　              #1-3  文字専用倉庫（DB=db_data）(※Django「setting.pyのDATABASES」と、Docker拡張機能「volume」で連結)。
      - static_volume:/usr/src/app/static/　　                                #1-4  CSS専用倉庫の連結命令(★本番/開発両方ともON) 
      - media_volume:/usr/src/app/media/　　　                                #1-5  画像専用倉庫の連結命令
    environment:                                                           #★2【変数化など】   
      - DEBUG=0　　　　　　　　　　　　　　　　　                             　 #2-1 デバック本番モードでは0(False) / 開発モードでは1(True)に設定】
      - MY_IP=${MY_IP}　　　　　　　　　　　　　                                #2-2 IPを変数化　
    command: gunicorn todoproject.wsgi:application --bind 0.0.0.0:8000 　　　 #2-3  Nginxのみ（Django内線番号8000番へ入る設定）

  nginx:　　　　　　　　　　　　　　　　　 　　　　　　　　　　　　　　　　　　   #★3【nginx:エリア(客を迎える80番窓口）】
    build: ./nginx　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　   #3-1　nginx (nginx/Dockerfile設計図)の2行目を元に、面玄関を組み立てろ」という命令
    ports:                            　　　　　　　　　　　　　　　　　　　　   #3-2　外部の80番から来た客を、このNginxの窓口の80番ポートにそのまま通せの指示
      - "80:80"
    volumes:　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　#★4【2つのコンテナ(NginxとDjango)を繋ぐ、★共有倉庫(=静的ファイル用css・画像用)】
      - static_volume:/usr/src/app/static/　　　　　　　　　　　　　　　　　 　  #4-1　Django側（又はNginx側）のcssを保存する格納倉庫(=/usr/src/app/static/)。 共有倉庫.荷物のやり取り場(=static_volume)
      - media_volume:/usr/src/app/media/　　　　　　　　　　　　　　　　　　 　  #4-2  ユーザーがアップロードした画像の保存場所(=/usr/src/app/media/)。　共有倉庫.荷物のやり取り場(=media_volume)
    depends_on:　　　　　　　　　　　　　                                   　  #4-3　web（Django）→Nginx等の★順番で起動しろ」命令(=起動の順番固定)
      - web　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　

volumes:　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　#★5【Dockerコンテナの影響受けずに(＝文字や画像保持の持続)、データ保存専用『倉庫の土台』をパソコン内に作れ」の全体宣言】
  media_volume:　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 #5-1 画像専用倉庫(ユーザーが投稿した画像等)」をコンテナが再起動しても消えず保存されるための本体を作る。
　db_volume:　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　      #5-2 文字専用倉庫の土台を自動作成(Dockerコンテナが再起動しても文字が消えない設定)
