# Generated by Django 6.0.2 on 2026-03-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('normal', '普通'), ('low', '低')], max_length=50, null=True),
        ),
    ]
