#Nginx専用(案内ルール)の設計図


#1,Nginxが、実務担当のDjangoさん（内線8000番）に。仕事を振るぞと認識するための設定
upstream django {
    server web:8000;
}

#2,お客さん用の正面玄関（80番）を開けて、総合受付する。
server {
    listen 80;
    server_name localhost;


#3,お客さんからのリクエストに,Nginxがお客さんのIPアドレスやドメイン名をメモし、Djangoにやさしく伝えてあげる。
    location / {
        proxy_pass http://django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

#4,Djangoは画像を配るのが苦手なので、代わりにNginxがCSS管理を行い、画面表示する(静的画面)
    location /static/ {
        alias /usr/src/app/static/;
    }

    location /media/ {
        alias /usr/src/app/media/;
    }
}
